### ISSUE TITLE
이 repo를 관리하기 귀찮으니 botwillacceptanything 를 통해서 +1을 2개 이상 받으면 그냥 머지해버립시다.

### ISSUE THREAD

**Issue by minhoryang** [SGCSRelease/slack_bot#4]
https://github.com/botwillacceptanything/botwillacceptanything good?

**Comment by minhoryang** [comment]
@JimJeon 어떻게 생각함?

**Comment by JimJeon** [comment]
@minhoryang 호오 좋은지는 써봐야 알거 같지만 재밌어보이네요. 재밌는건 대찬성!!

**Comment by minhoryang** [comment]
아;ㅅ; botwillacceptanything는 자신을 fork해야지만 머지하네요 ;ㅅ;ㅠ
다른걸 찾아보겠습니다.

**Comment by minhoryang** [comment]
코드를 조금 수정해서 해당 directory를 바라보도록 할 수 있을 것 같아요!

**Comment by minhoryang** [comment]
테스트를 하느라 pr에 comment를 도배하고있는데 지울게요...

**Comment by minhoryang** [comment]
자동머지가 되는지 안되는지 모르겠어요.

**Comment by JimJeon** [comment]
0579319e0fdc574c24a5f76b24b32a3b9430fe36는 자동머지가 아닌건가요

**Comment by minhoryang** [comment]
아 그거 자동머지프로그램을재시작해서 수동머지한거에요;;;;

**Comment by minhoryang** [comment]
```bash
TARGET_REPO=../slack_bot/ node main.js
HOME=/tmp ngrok http 3000 --region ap
```
